
[server]
port = 8501
address = "localhost"
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "localhost"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"
